# Generated by Django 5.0.2 on 2024-02-29 20:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_application', '0002_productuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupstudent',
            options={'verbose_name': 'Студент группы', 'verbose_name_plural': 'Студенты группы'},
        ),
        migrations.AlterModelOptions(
            name='productuser',
            options={'verbose_name': 'Студент курса', 'verbose_name_plural': 'Студенты курса'},
        ),
        migrations.AlterUniqueTogether(
            name='groupstudent',
            unique_together={('user', 'group')},
        ),
    ]
